In [1]:
import pandas as pd  
import numpy as np

In [16]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
T20_data = pd.read_csv("IPL Ball-by-Ball 2008-2020.csv")
T20_data = T20_data.sort_values(['id', 'inning', 'over', 'ball'])
T20_data = T20_data.reset_index(drop=True)
T20_data.head()

id  inning  over  ball      batsman  non_striker   bowler  \
0  335982       1     0     1   SC Ganguly  BB McCullum  P Kumar   
1  335982       1     0     2  BB McCullum   SC Ganguly  P Kumar   
2  335982       1     0     3  BB McCullum   SC Ganguly  P Kumar   
3  335982       1     0     4  BB McCullum   SC Ganguly  P Kumar   
4  335982       1     0     5  BB McCullum   SC Ganguly  P Kumar   

   batsman_runs  extra_runs  total_runs  non_boundary  is_wicket  \
0             0           1           1             0          0   
1             0           0           0             0          0   
2             0           1           1             0          0   
3             0           0           0             0          0   
4             0           0           0             0          0   

  dismissal_kind player_dismissed fielder extras_type           batting_team  \
0            NaN              NaN     NaN     legbyes  Kolkata Knight Riders   
1            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
2            NaN              NaN     NaN       wides  Kolkata Knight Riders   
3            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
4            NaN              NaN     NaN         NaN  Kolkata Knight Riders   

                  bowling_team  
0  Royal Challengers Bangalore  
1  Royal Challengers Bangalore  
2  Royal Challengers Bangalore  
3  Royal Challengers Bangalore  
4  Royal Challengers Bangalore

In [18]:
T20_data.shape

(193468, 18)

In [19]:
T20_innings1_data = T20_data.loc[T20_data['inning'] == 1]
T20_innings1_data = T20_innings1_data.reset_index(drop=True)
T20_innings1_data

id  inning  over  ball      batsman  non_striker  \
0        335982       1     0     1   SC Ganguly  BB McCullum   
1        335982       1     0     2  BB McCullum   SC Ganguly   
2        335982       1     0     3  BB McCullum   SC Ganguly   
3        335982       1     0     4  BB McCullum   SC Ganguly   
4        335982       1     0     5  BB McCullum   SC Ganguly   
...         ...     ...   ...   ...          ...          ...   
100186  1237181       1    19     2     AR Patel      SS Iyer   
100187  1237181       1    19     3      SS Iyer     K Rabada   
100188  1237181       1    19     4      SS Iyer     K Rabada   
100189  1237181       1    19     5      SS Iyer     K Rabada   
100190  1237181       1    19     6      SS Iyer     K Rabada   

                 bowler  batsman_runs  extra_runs  total_runs  non_boundary  \
0               P Kumar             0           1           1             0   
1               P Kumar             0           0           0             0   
2               P Kumar             0           1           1             0   
3               P Kumar             0           0           0             0   
4               P Kumar             0           0           0             0   
...                 ...           ...         ...         ...           ...   
100186  NM Coulter-Nile             0           0           0             0   
100187  NM Coulter-Nile             0           0           0             0   
100188  NM Coulter-Nile             0           0           0             0   
100189  NM Coulter-Nile             6           0           6             0   
100190  NM Coulter-Nile             1           0           1             0   

        is_wicket dismissal_kind player_dismissed       fielder extras_type  \
0               0            NaN              NaN           NaN     legbyes   
1               0            NaN              NaN           NaN         NaN   
2               0            NaN              NaN           NaN       wides   
3               0            NaN              NaN           NaN         NaN   
4               0            NaN              NaN           NaN         NaN   
...           ...            ...              ...           ...         ...   
100186          1         caught         AR Patel  AS Roy (sub)         NaN   
100187          0            NaN              NaN           NaN         NaN   
100188          0            NaN              NaN           NaN         NaN   
100189          0            NaN              NaN           NaN         NaN   
100190          1        run out         K Rabada           NaN         NaN   

                 batting_team                 bowling_team  
0       Kolkata Knight Riders  Royal Challengers Bangalore  
1       Kolkata Knight Riders  Royal Challengers Bangalore  
2       Kolkata Knight Riders  Royal Challengers Bangalore  
3       Kolkata Knight Riders  Royal Challengers Bangalore  
4       Kolkata Knight Riders  Royal Challengers Bangalore  
...                       ...                          ...  
100186         Delhi Capitals               Mumbai Indians  
100187         Delhi Capitals               Mumbai Indians  
100188         Delhi Capitals               Mumbai Indians  
100189         Delhi Capitals               Mumbai Indians  
100190         Delhi Capitals               Mumbai Indians  

[100191 rows x 18 columns]

### Innings 1 table

In [20]:
T20_runs = T20_innings1_data.loc[(T20_innings1_data['extra_runs'] == 0) & (T20_innings1_data['is_wicket'] == 0)]
T20_extra = T20_innings1_data.loc[(T20_innings1_data['extra_runs'] > 0) & (T20_innings1_data['is_wicket'] == 0)]
T20_wicket = T20_innings1_data.loc[T20_innings1_data['is_wicket'] != 0]

In [23]:
innings1_results_table = pd.DataFrame({'Outcome': pd.Series(dtype='str'),
                   'T20_prob': pd.Series(dtype='float')})
for i in range(7):
    #print("Probability of scoring " + str(i) + " run : " + str(T20_data['batsman_runs'].value_counts()[i]/T20_data.shape[0]*100))
    innings1_results_table = innings1_results_table.append({'Outcome': str(i), 'T20_prob': T20_runs['batsman_runs'].value_counts()[i]/T20_innings1_data.shape[0]*100},ignore_index=True)

innings1_results_table = innings1_results_table.append({'Outcome': 'extra runs', 'T20_prob': T20_extra.shape[0]/T20_innings1_data.shape[0]*100},ignore_index=True)
innings1_results_table = innings1_results_table.append({'Outcome': 'wicket', 'T20_prob':T20_wicket.shape[0]/T20_innings1_data.shape[0]* 100},ignore_index=True)
innings1_results_table

Outcome   T20_prob
0           0  29.828028
1           1  37.108123
2           2   6.527532
3           3   0.319390
4           4  11.289437
5           5   0.027947
6           6   4.664092
7  extra runs   5.306864
8      wicket   4.928586

In [22]:
innings1_results_table['T20_prob'].values

array([2.98280285e+01, 3.71081235e+01, 6.52753241e+00, 3.19389965e-01,
       1.12894372e+01, 2.79466220e-02, 4.66409159e+00, 5.30686389e+00,
       4.92858640e+00])

In [29]:
extras_table = pd.DataFrame({'Runs Scored': pd.Series(dtype='str'),
                   'prob': pd.Series(dtype='float')})
for i in range(1,8):
    if(i==6):
        extras_table = extras_table.append({'Runs Scored': str(i), 'prob': 0},ignore_index=True)
    else:
    #print("Probability of scoring " + str(i) + " run : " + str(T20_data['batsman_runs'].value_counts()[i]/T20_data.shape[0]*100))
        extras_table = extras_table.append({'Runs Scored': str(i), 'prob': T20_extra['total_runs'].value_counts()[i]/T20_extra.shape[0]*100},ignore_index=True)

extras_table

Runs Scored       prob
0           1  84.803461
1           2   6.751928
2           3   1.203686
3           4   3.404175
4           5   3.310137
5           6   0.000000
6           7   0.526613

In [30]:
extras_table['prob'].values

array([84.8034606 ,  6.75192778,  1.20368629,  3.40417529,  3.3101373 ,
        0.        ,  0.52661275])

In [34]:
wickets_table = pd.DataFrame({'Runs Scored': pd.Series(dtype='str'),
                   'prob': pd.Series(dtype='float')})
for i in range(3):
#     if(i==6):
#         wickets_table = wickets_table.append({'Runs Scored': str(i), 'prob': 0},ignore_index=True)
#     else:
    #print("Probability of scoring " + str(i) + " run : " + str(T20_data['batsman_runs'].value_counts()[i]/T20_data.shape[0]*100))
        wickets_table = wickets_table.append({'Runs Scored': str(i), 'prob': T20_wicket['total_runs'].value_counts()[i]/T20_extra.shape[0]*100},ignore_index=True)

wickets_table

Runs Scored       prob
0           0  89.110401
1           1   3.592251
2           2   0.169268

In [35]:
wickets_table['prob'].values

array([89.1104006 ,  3.59225127,  0.16926838])